# Generated by Django 5.0.6 on 2025-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_skill_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
